name = "PopGen"
uuid = "7ad8bbce-b930-4859-a320-8d110fabc8c7"
authors = ["Olivier Labayle <olabayle@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
